name: ti_boulo
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_tagging: ^2.2.0+3
  date_range_picker: ^1.0.6
  google_map_location_picker: ^3.2.1+1
  intl:
  intl_translation:
  google_maps_place_picker: ^0.7.0
  getflutter: ^1.0.8
  flutter_staggered_grid_view: "^0.3.0"
  introduction_screen: ^1.0.7
  cupertino_icons: ^0.1.2
  convex_bottom_bar: ^2.1.0+1
  image_picker:
  animated_text_kit: ^2.0.0
  dio:
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
